services:
  - type: web
    name: edtech-backend
    runtime: python
    plan: free
    
    buildCommand: pip install -r requirements.txt
  
    startCommand: |
      python manage.py migrate &&
      python manage.py loaddata fixtures/topics.yaml &&
      python manage.py loaddata fixtures/lessons.yaml &&
      python manage.py loaddata fixtures/quizzes.yaml &&
      python manage.py loaddata fixtures/questions.yaml &&
      python manage.py collectstatic --noinput &&
      gunicorn edtech.wsgi:application

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: GROQ_API_KEY
        sync: false
